Waterworks/Controllers/MapController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using NetTopologySuite.Features;
using NetTopologySuite.Geometries;
using Waterworks.Models;
using System.Collections.Generic;
using Waterworks.Data;
using Waterworks.Models.View;
using Waterworks.Models.Db.Waterworks;

namespace Waterworks.Controllers
{
    public class MapController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public MapController(ApplicationDbContext context)
        {
            dbContext = context;
        }
        public IActionResult Index()
        {
            var pointsList = dbContext.Obiekt.ToList();
            List<PointFeature> pointList = new List<PointFeature>();
            foreach (Obiekt o in pointsList)
            {
                pointList.Add(new PointFeature(o.Id, o.Geometria));
            }
            return View("~/Views/Map/Index.cshtml", pointList);
        }
    }
}

Waterworks/Controllers/ObjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Waterworks.Models.View.Client;
using Waterworks.Models;
using NetTopologySuite.Geometries;
using NetTopologySuite.IO;
using Microsoft.EntityFrameworkCore;
using Waterworks.Data;
using Waterworks.Models.Db.Waterworks;
using Newtonsoft.Json.Linq;
using Waterworks.Models.View.Object;
using X.PagedList;
using Waterworks.Models.View;
using Waterworks.Models.View.WaterMeter;

namespace Waterworks.Controllers
{
    public class ObjectController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public ObjectController(ApplicationDbContext context)
        {
            dbContext = context;
        }
        public IActionResult About(int objectId)
        {
            return PartialView();
        }
        public IActionResult Index(string sortOrder, string currentCategory, string category, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["IdSortParam"] = String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";
            ViewData["HouseNumberSortParam"] = sortOrder == "HouseNumber" ? "HouseNumber_desc" : "HouseNumber";
            ViewData["StreetSortParam"] = sortOrder == "Street" ? "Street_desc" : "Street";
            ViewData["PostalCodeSortParam"] = sortOrder == "PostalCode" ? "PostalCode_desc" : "PostalCode";
            ViewData["ApartmentNumberSortParam"] = sortOrder == "ApartmentNumber" ? "ApartmentNumber_desc" : "ApartmentNumber";
            ViewData["PlotNumberSortParam"] = sortOrder == "PlotNumber" ? "PlotNumber_desc" : "PlotNumber";
            ViewData["PostSortParam"] = sortOrder == "Post" ? "Post_desc" : "Post";
            ViewData["PayoffSortParam"] = sortOrder == "Payoff" ? "Payoff_desc" : "Payoff";
            ViewData["CitySortParam"] = sortOrder == "City" ? "City_desc" : "City";
            ViewData["ClientIdSortParam"] = sortOrder == "ClientId" ? "ClientId_desc" : "ClientId";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                category = currentCategory;
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentCategory"] = category;
            var objects = dbContext.Obiekt
                .Include(o => o.AdresObiektu)
                .ToList();

            List<BasicCreateObjectViewModel> list = new List<BasicCreateObjectViewModel>();

            if (!String.IsNullOrWhiteSpace(searchString)) {
                searchString = searchString.ToUpper();
                //objects = objects.Where(o => o.AdresObiektu.First().Miejscowosc.ToUpper().Contains(searchString) ||
                //o.AdresObiektu.First().KodPocztowy.ToUpper().Contains(searchString) ||
                //o.AdresObiektu.First().NrDomu.ToUpper().Contains(searchString) ||
                //o.AdresObiektu.First().NrLokalu.ToUpper().Contains(searchString) ||
                //o.AdresObiektu.First().Ulica.ToUpper().Contains(searchString) ||
                //o.AdresObiektu.First().NrDzialki.ToUpper().Contains(searchString) ||
                //o.AdresObiektu.First().Poczta.ToUpper().Contains(searchString) ||
                //o.SposobRozliczenia.ToUpper().Contains(searchString)
                //)
                //.ToList();
                if (currentCategory == "KodPocztowy")
                    objects = objects.Where(o => o.AdresObiektu.First().KodPocztowy.ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "Miejscowosc")
                    objects = objects.Where(o => o.AdresObiektu.First().Miejscowosc.ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "NrDomu")
                    objects = objects.Where(o => o.AdresObiektu.First().NrDomu.ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "NrLokalu")
                    objects = objects.Where(o => o.AdresObiektu.First().NrLokalu.ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "Ulica")
                    objects = objects.Where(o => o.AdresObiektu.First().Ulica.ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "NrDzialki")
                    objects = objects.Where(o => o.AdresObiektu.First().NrDzialki.ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "Poczta")
                    objects = objects.Where(o => o.AdresObiektu.First().Poczta.ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "SposobRozliczenia")
                    objects = objects.Where(o => o.SposobRozliczenia.ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "IdKlienta")
                    objects = objects.Where(o => o.KlientIdKlienta.ToString().ToUpper().Contains(searchString)).ToList();
                else
                    objects = objects.Where(o => o.Id.ToString().ToUpper().Contains(searchString)).ToList();
            }
            foreach (var objectItem in objects)
            {
                BasicCreateObjectViewModel tempObject = new BasicCreateObjectViewModel
                {
                    NumerKlienta = objectItem.KlientIdKlienta,
                    KodPocztowy = objectItem.AdresObiektu.First().KodPocztowy,
                    Miejscowosc = objectItem.AdresObiektu.First().Miejscowosc,
                    NrDomu = objectItem.AdresObiektu.First().NrDomu,
                    NrLokalu = objectItem.AdresObiektu.First().NrLokalu,
                    NrDzialki = objectItem.AdresObiektu.First().NrDzialki,
                    Poczta = objectItem.AdresObiektu.First().Poczta,
                    SposobRozliczenia = objectItem.SposobRozliczenia.ToString(),
                    Ulica = objectItem.AdresObiektu.First().Ulica,
                    Geometria = objectItem.Geometria.ToString(),
                    Id = objectItem.Id,
                };
                list.Add(tempObject);
            }
            switch (sortOrder)
            {
                case "Id_desc":
                    list = list.OrderByDescending(o => o.Id).ToList();
                    break;
                case "HouseNumber":
                    list = list.OrderBy(o => o.NrDomu).ToList();
                    break;
                case "HouseNumber_desc":
                    list = list.OrderByDescending(o => o.NrDomu).ToList();
                    break;
                case "Street":
                    list = list.OrderBy(o => o.Ulica).ToList();
                    break;
                case "Street_desc":
                    list = list.OrderByDescending(o => o.Ulica).ToList();
                    break;
                case "PostalCode":
                    list = list.OrderBy(o => o.KodPocztowy).ToList();
                    break;
                case "PostalCode_desc":
                    list = list.OrderByDescending(o => o.KodPocztowy).ToList();
                    break;
                case "ApartmentNumber":
                    list = list.OrderBy(o => o.NrLokalu).ToList();
                    break;
                case "ApartmentNumber_desc":
                    list = list.OrderByDescending(o => o.NrLokalu).ToList();
                    break;
                case "PlotNumber":
                    list = list.OrderBy(o => o.NrDzialki).ToList();
                    break;
                case "PlotNumber_desc":
                    list = list.OrderByDescending(o => o.NrDzialki).ToList();
                    break;
                case "Post":
                    list = list.OrderBy(o => o.Poczta).ToList();
                    break;
                case "Post_desc":
                    list = list.OrderByDescending(o => o.Poczta).ToList();
                    break;
                case "Payoff":
                    list = list.OrderBy(o => o.SposobRozliczenia).ToList();
                    break;
                case "Payoff_desc":
                    list = list.OrderByDescending(o => o.SposobRozliczenia).ToList();
                    break;
                case "City":
                    list = list.OrderBy(o => o.Miejscowosc).ToList();
                    break;
                case "City_desc":
                    list = list.OrderByDescending(o => o.Miejscowosc).ToList();
                    break;
                case "ClientId":
                    list = list.OrderBy(o => o.NumerKlienta).ToList();
                    break;
                case "ClientId_desc":
                    list = list.OrderByDescending(o => o.NumerKlienta).ToList();
                    break;
                default:
                    list = list.OrderBy(o => o.Id).ToList();
                    break;
            }
            //List<ClientBasicInformation> list = new List<ClientBasicInformation>();
            //var clients = dbContext.Klient
            //    .Include(k => k.IdentyfikatorPodatkowy)
            //    .ToList();
            //foreach (var client in clients)
            //{
            //    ClientBasicInformation tempClient = new ClientBasicInformation
            //    {
            //        ClientId = client.IdKlienta,
            //        NIP = client.IdentyfikatorPodatkowy.First().Nip,
            //        PESEL = client.IdentyfikatorPodatkowy.First().Pesel,
            //        RodzajKlientaId = (ContractorType)client.RodzajKlientaId
            //    };
            //    list.Add(tempClient);
            //}
            int pageSize = 10;    
            return View(PaginatedList<BasicCreateObjectViewModel>.CreateAsync(list.AsQueryable<BasicCreateObjectViewModel>(), page ?? 1, pageSize));
        }
        public IActionResult Create()
        {

Waterworks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wodociągi</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img src="~/images/pinezka.png" class="img-rounded" height="30" width="30" style="margin-top:7%" />
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    Wodociągi
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Admin" asp-action="Index">Panel Admina</a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Map" asp-action="Index">Mapa</a></li>
                        <li><a asp-area="" asp-controller="Client" asp-action="Index">Kartoteka kontrahentów</a></li>
                        <li><a asp-area="" asp-controller="Object" asp-action="Index">Kartoteka obiektów</a></li>
                        <li><a asp-area="" asp-controller="WaterMeter" asp-action="Index">Kartoteka wodomierzy</a></li>
                        <li><a asp-area="" asp-controller="Contract" asp-action="Index">Umowy</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Wodociągi</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>