Waterworks/Models/Db/Waterworks/PriceList/CennikScieki.cs
using System;
using System.Collections.Generic;

namespace Waterworks.Models.Db.Waterworks
{
    public partial class CennikScieki
    {
        public int Id { get; set; }
        public float CenaZaM3 { get; set; }
        public int RodzajKlientaId { get; set; }
        public string NazwaCennika { get; set; }
        public string TypCennika { get; set; }

        public RodzajKlienta RodzajKlienta { get; set; }
    }
}

Waterworks/Models/Db/Waterworks/PriceList/CennikWoda.cs
using System;
using System.Collections.Generic;

namespace Waterworks.Models.Db.Waterworks
{
    public partial class CennikWoda
    {
        public int Id { get; set; }
        public float CenaZaM3 { get; set; }
        public int RodzajKlientaId { get; set; }
        public string NazwaCennika { get; set; }
        public string TypCennika { get; set; }

        public RodzajKlienta RodzajKlienta { get; set; }
    }
}

Waterworks/Models/Db/Waterworks/PriceList/NormyZuzyciaWody.cs
using System;
using System.Collections.Generic;

namespace Waterworks.Models.Db.Waterworks
{
    public partial class NormyZuzyciaWody
    {
        public int Id { get; set; }
        public float ZuzycieM3NaMiesiac { get; set; }
        public int NazwaNormy { get; set; }
        public int ZuzycieDm3NaDobe { get; set; }
        public int RodzajKlientaId { get; set; }
        public string OpisNormy { get; set; }
        public string TypNormy { get; set; }

        public RodzajKlienta RodzajKlienta { get; set; }
    }
}

Waterworks/Models/Db/Waterworks/PriceList/OplatyAbonamentoweScieki.cs
using System;
using System.Collections.Generic;

namespace Waterworks.Models.Db.Waterworks
{
    public partial class OplatyAbonamentoweScieki
    {
        public int Id { get; set; }
        public string OkresRozliczeniowy { get; set; }
        public float Oplata { get; set; }
        public int RodzajKlientaId { get; set; }
        public string Nazwa { get; set; }
        public string TypCennika { get; set; }

        public RodzajKlienta RodzajKlienta { get; set; }
    }
}

Waterworks/Models/Db/Waterworks/PriceList/OplatyAbonamentoweWoda.cs
using System;
using System.Collections.Generic;

namespace Waterworks.Models.Db.Waterworks
{
    public partial class OplatyAbonamentoweWoda
    {
        public int Id { get; set; }
        public string OkresRozliczeniowy { get; set; }
        public float Oplata { get; set; }
        public int RodzajKlientaId { get; set; }
        public string Nazwa { get; set; }
        public string TypCennika { get; set; }

        public RodzajKlienta RodzajKlienta { get; set; }
    }
}

Waterworks/Models/View/PriceList/PriceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Waterworks.Models.View.PriceList
{
    public class PriceViewModel
    {
        [Display(Name = "Id cennika")]
        public int Id { get; set; }
        [Display(Name = "Cena za m3")]
        public float CenaZaM3 { get; set; }
        [Display(Name = "Rodzaj klienta")]
        public string RodzajKlienta { get; set; }

        public int RodzajKlientaId { get; set; }
        [Display(Name = "Nazwa cennika")]
        public string NazwaCennika { get; set; }
        [Display(Name = "Typ cennika")]
        public string TypCennika { get; set; }
    }
}

Waterworks/Models/View/PriceList/SubscriptionPriceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Waterworks.Models.View.PriceList
{
    public class SubscriptionPriceViewModel
    {
        [Display(Name = "Id cennika")]
        public int Id { get; set; }

        [Display(Name = "Okres rozliczeniowy")]
        public string OkresRozliczeniowy { get; set; }

        [Display(Name = "Opłata")]
        public float Oplata { get; set; }

        [Display(Name = "Rodzaj klienta")]
        public string RodzajKlienta { get; set; }
        public int RodzajKlientaId { get; set; }

        [Display(Name = "Nazwa cennika")]
        public string NazwaCennika { get; set; }

        [Display(Name = "Typ cennika")]
        public string TypCennika { get; set; }
    }
}

Waterworks/Controllers/Admin/Prices/PriceListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Waterworks.Data;
using Waterworks.Models.Db.Waterworks;
using Waterworks.Models.View.PriceList;

namespace Waterworks.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class PriceListController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public PriceListController(ApplicationDbContext context)
        {
            dbContext = context;
        }
        public IActionResult WaterPriceList()
        {
            List<PriceViewModel> list = new List<PriceViewModel>();
            var priceLists = dbContext.CennikWoda
                .Join(dbContext.RodzajKlienta,
                    o => o.RodzajKlientaId,
                    a => a.Id,
                    (o, a) => new { CennikWoda = o, RodzajKlienta = a }
                    ).ToList();

            foreach (var item in priceLists)
            {
                PriceViewModel tempObject = new PriceViewModel
                {
                    Id = item.CennikWoda.Id,
                    CenaZaM3 = item.CennikWoda.CenaZaM3,
                    NazwaCennika = item.CennikWoda.NazwaCennika,
                    TypCennika = item.CennikWoda.TypCennika,
                    RodzajKlienta = item.RodzajKlienta.TypKlienta,
                    RodzajKlientaId = item.RodzajKlienta.Id
                };
                list.Add(tempObject);
            }
            return PartialView("~/Views/PriceList/Water/_List.cshtml", list);
        }

        [HttpGet]
        public IActionResult WaterPriceCreate()
        {
            List<string> clientTypes = new List<string> { "osoba fizyczna", "podmiot gospodarczy" };
            ViewBag.clientTypesList = clientTypes;
            return View("~/Views/PriceList/Water/Create.cshtml");
        }

        [HttpPost]
        public IActionResult WaterPriceCreate([Bind] PriceViewModel priceItem)
        {

            var item = new CennikWoda()
            {
                NazwaCennika = priceItem.NazwaCennika,
                CenaZaM3 = priceItem.CenaZaM3,
                RodzajKlientaId = priceItem.RodzajKlientaId,
                TypCennika = priceItem.TypCennika
            };
            dbContext.CennikWoda.Add(item);
            dbContext.SaveChanges();

            return RedirectToAction("Admin", "Index");
        }

        public IActionResult SewagePriceList()
        {
            List<PriceViewModel> list = new List<PriceViewModel>();
            var priceLists = dbContext.CennikScieki 
                .Join(dbContext.RodzajKlienta,
                    o => o.RodzajKlientaId,
                    a => a.Id,
                    (o, a) => new { CennikScieki = o, RodzajKlienta = a }
                    ).ToList();

            foreach (var item in priceLists)
            {
                PriceViewModel tempObject = new PriceViewModel
                {
                    Id = item.CennikScieki.Id,
                    CenaZaM3 = item.CennikScieki.CenaZaM3,
                    NazwaCennika = item.CennikScieki.NazwaCennika,
                    TypCennika = item.CennikScieki.TypCennika,
                    RodzajKlienta = item.RodzajKlienta.TypKlienta,
                    RodzajKlientaId = item.RodzajKlienta.Id
                };
                list.Add(tempObject);
            }
            return PartialView("~/Views/PriceList/Sewage/_List.cshtml", list);
        }

        [HttpGet]
        public IActionResult SewagePriceCreate()
        {
            List<string> clientTypes = new List<string> { "osoba fizyczna", "podmiot gospodarczy" };
            ViewBag.clientTypesList = clientTypes;
            return View("~/Views/PriceList/Sewage/Create.cshtml");
        }

        [HttpPost]
        public IActionResult SewagePriceCreate([Bind] PriceViewModel priceItem)
        {

            var item = new CennikScieki()
            {
                NazwaCennika = priceItem.NazwaCennika,
                CenaZaM3 = priceItem.CenaZaM3,
                RodzajKlientaId = priceItem.RodzajKlientaId,
                TypCennika = priceItem.TypCennika
            };
            dbContext.CennikScieki.Add(item);
            dbContext.SaveChanges();

            return RedirectToAction("Admin", "Index");
        }
    }
}

Waterworks/Views/PriceList/Sewage/Create.cshtml
@model Waterworks.Models.View.PriceList.PriceViewModel

@{
    ViewData["Title"] = "Nowy cennik";
}

<h2>Utwórz nowy cennik</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SewagePriceCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="col-xs-5">
                    <label asp-for="RodzajKlientaId" class="radio-inline">
                        <input type="radio" asp-for="RodzajKlientaId" name="RodzajKlientaId" value="1" />
                        Osoba fizyczna
                    </label>
                </div>
                <div class="col-xs-5">
                    <label asp-for="RodzajKlientaId" class="radio-inline">
                        <input type="radio" asp-for="RodzajKlientaId" name="RodzajKlientaId" value="2" checked />
                        Podmiot gospodarczy
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CenaZaM3" class="control-label"></label>
                <input asp-for="CenaZaM3" class="form-control" />
                <span asp-validation-for="CenaZaM3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NazwaCennika" class="control-label"></label>
                <input asp-for="NazwaCennika" class="form-control" />
                <span asp-validation-for="NazwaCennika" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypCennika" class="control-label"></label>
                <input asp-for="TypCennika" class="form-control" />
                <span asp-validation-for="TypCennika" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="SewagePriceList">Back to List</a>
</div>

Waterworks/Views/PriceList/Sewage/List.cshtml
@model IEnumerable<Waterworks.Models.View.PriceList.PriceViewModel>
@{
    ViewData["Title"] = "Panel admina";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Index</h2>
<p>
    <a asp-action="SewagePriceCreate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CenaZaM3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RodzajKlienta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NazwaCennika)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypCennika)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CenaZaM3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RodzajKlienta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NazwaCennika)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypCennika)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Waterworks/Views/PriceList/Sewage/_List.cshtml
@model IEnumerable<Waterworks.Models.View.PriceList.PriceViewModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CenaZaM3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RodzajKlienta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RodzajKlientaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NazwaCennika)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypCennika)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CenaZaM3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RodzajKlienta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RodzajKlientaId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NazwaCennika)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypCennika)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edytuj</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
            </td>
        </tr>
}
    </tbody>
</table>
<p>
    <a asp-action="SewagePriceCreate" asp-controller="PriceList" class="btn btn-primary">Utwórz nowy</a>
</p>