Waterworks/Models/View/WaterMeter/AttachWaterMeterToObjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Waterworks.Models.View.WaterMeter
{
    public class AttachWaterMeterToObjectViewModel
    {
        [Display(Name = "Nr wodomierza")]
        public string NrWodomierza { get; set; }

        [Display(Name = "Typ wodomierza")]
        public string TypWodomierza { get; set; }

        [RegularExpression("[0-9]+")]
        [Display(Name = "Id obiektu")]
        public int? IdObiektu { get; set; }
    }
}

Waterworks/Models/View/WaterMeter/ChangeWaterMeterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Waterworks.Models.View.WaterMeter
{
    public class ChangeWaterMeterViewModel
    {
        [Display(Name = "Nr wodomierza")]
        public string NrWodomierza { get; set; }

        [Display(Name = "Typ wodomierza")]
        public string TypWodomierza { get; set; }

        [Display(Name = "Nr nowego wodomierza")]
        public string NrNowegoWodomierza { get; set; }

        [RegularExpression("[0-9]+")]
        [Display(Name = "Id obiektu")]
        public int? IdObiektu { get; set; }
    }
}

Waterworks/Models/View/WaterMeter/WaterMeterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Waterworks.Models.View.WaterMeter
{
    public class WaterMeterViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Nr wodomierza")]
        public string NrWodomierza { get; set; }
        [Display(Name = "Data legalizacji")]
        public DateTime DataLegalizacji { get; set; }
        [Display(Name = "Data ewidencji")]
        public DateTime DataEwidencji { get; set; }
        [Display(Name = "Id obiektu")]
        public int? ObiektId { get; set; }
        [Display(Name = "Typ wodomierza")]
        public string TypWodomierza{get; set;}
    }
}

Waterworks/Controllers/WaterMeterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Waterworks.Data;
using Waterworks.Models.View.WaterMeter;

namespace Waterworks.Controllers
{   
    public class WaterMeterController : Controller
    {
        private readonly ApplicationDbContext dbContext;
        public WaterMeterController(ApplicationDbContext context)
        {
            dbContext = context;
        }
        public IActionResult Index(string sortOrder, string currentCategory, string category, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["WaterMeterNumberSortParam"] = String.IsNullOrEmpty(sortOrder) ? "WaterMeterNumber_desc" : "";
            ViewData["ObjectIdSortParam"] = sortOrder == "ObjectId" ? "ObjectId_desc" : "ObjectId";
            ViewData["LegalizationDateSortParam"] = sortOrder == "LegalizationDate" ? "LegalizationDate_desc" : "LegalizationDate";
            ViewData["RecordDateSortParam"] = sortOrder == "RecordDate" ? "RecordDate_desc" : "RecordDate";
            ViewData["WaterMeterTypeSortParam"] = sortOrder == "WaterMeterType" ? "WaterMeterType_desc" : "WaterMeterType";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                category = currentCategory;
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentCategory"] = category;
            List<WaterMeterViewModel> list = new List<WaterMeterViewModel>();
            var waterMeters = dbContext.Wodomierz.ToList();
            if (!String.IsNullOrWhiteSpace(searchString))
            {
                searchString = searchString.ToUpper();
                if (currentCategory == "IdObiektu")
                    waterMeters = waterMeters.Where(o => o.ObiektId.ToString().ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "DataLegalizacji")
                    waterMeters = waterMeters.Where(o => o.DataLegalizacji.ToString().ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "DataEwidencji")
                    waterMeters = waterMeters.Where(o => o.DataEwidencji.ToString().ToUpper().Contains(searchString)).ToList();
                else if (currentCategory == "TypWodomierza")
                    waterMeters = waterMeters.Where(o => o.TypWodomierza.ToUpper().Contains(searchString)).ToList();
                else
                    waterMeters = waterMeters.Where(o => o.NrWodomierza.ToUpper().Contains(searchString)).ToList();
            }
            foreach (var objectItem in waterMeters)
            {
                WaterMeterViewModel tempObject = new WaterMeterViewModel
                {
                    Id = objectItem.Id,
                    NrWodomierza = objectItem.NrWodomierza,
                    DataEwidencji = objectItem.DataEwidencji,
                    DataLegalizacji = objectItem.DataLegalizacji,
                    ObiektId = objectItem.ObiektId,
                    TypWodomierza = objectItem.TypWodomierza
                };
                list.Add(tempObject);
            }
            switch (sortOrder)
            {
                case "WaterMeterNumber_desc":
                    list = list.OrderByDescending(o => o.NrWodomierza).ToList();
                    break;
                case "ObjectId":
                    list = list.OrderBy(o => o.ObiektId).ToList();
                    break;
                case "ObjectId_desc":
                    list = list.OrderByDescending(o => o.ObiektId).ToList();
                    break;
                case "LegalizationDate":
                    list = list.OrderBy(o => o.DataLegalizacji).ToList();
                    break;
                case "LegalizationDate_desc":
                    list = list.OrderByDescending(o => o.DataLegalizacji).ToList();
                    break;
                case "RecordDate":
                    list = list.OrderBy(o => o.DataEwidencji).ToList();
                    break;
                case "RecordDate_desc":
                    list = list.OrderByDescending(o => o.DataEwidencji).ToList();
                    break;
                case "WaterMeterType":
                    list = list.OrderBy(o => o.TypWodomierza).ToList();
                    break;
                case "WaterMeterType_desc":
                    list = list.OrderByDescending(o => o.TypWodomierza).ToList();
                    break;
                default:
                    list = list.OrderBy(o => o.NrWodomierza).ToList();
                    break;
            }
            int pageSize = 10;
            return View(PaginatedList<WaterMeterViewModel>.CreateAsync(list.AsQueryable<WaterMeterViewModel>(), page ?? 1, pageSize));
        }
        public IActionResult List(int id) {
            List<WaterMeterViewModel> list = new List<WaterMeterViewModel>();
            var waterMeters = dbContext.Wodomierz.Where(w => w.ObiektId == id).ToList();
            foreach (var objectItem in waterMeters)
            {
                WaterMeterViewModel tempObject = new WaterMeterViewModel
                {
                    Id = objectItem.Id,
                    NrWodomierza = objectItem.NrWodomierza,
                    DataEwidencji = objectItem.DataEwidencji,
                    DataLegalizacji = objectItem.DataLegalizacji,
                    ObiektId = objectItem.ObiektId,
                    TypWodomierza = objectItem.TypWodomierza
                };
                list.Add(tempObject);
            }
            return PartialView("~/Views/WaterMeter/_List.cshtml", list);
        }
        public IActionResult DetachWaterMeter(int id)
        {
            var waterMeter = dbContext.Wodomierz.Where(w => w.Id == id).First();
            var objectId = waterMeter.ObiektId;

            return RedirectToAction("AdvancedDetails/" + objectId, "Object");
        }

        public IActionResult ChangeWaterMeter(int objectId, string oldWaterMeterNumber, string oldWaterMeterType) {
            
            var model = new ChangeWaterMeterViewModel{ IdObiektu = objectId, NrWodomierza = oldWaterMeterNumber, TypWodomierza = oldWaterMeterType};
            return PartialView("_ChangeWaterMeterModalPartial", model);
        }
        [HttpPost]
        public IActionResult ChangeWaterMeter(ChangeWaterMeterViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(model.NrNowegoWodomierza))
                {
                    var newWaterMeter = dbContext.Wodomierz.Where(w => w.NrWodomierza == model.NrNowegoWodomierza).ToList();
                    if (newWaterMeter.Count >= 1)
                    {
                        var item = newWaterMeter.Single();
                        if (!item.ObiektId.HasValue)
                        {
                            item.ObiektId = model.IdObiektu;
                            item.TypWodomierza = model.TypWodomierza;
                            dbContext.Wodomierz.Update(item);

                            var oldWaterMeter = dbContext.Wodomierz.Where(w => w.NrWodomierza == model.NrWodomierza).First();
                            oldWaterMeter.ObiektId = null;
                            oldWaterMeter.TypWodomierza = "WOLNY";
                            dbContext.Wodomierz.Update(oldWaterMeter);

                            dbContext.SaveChanges();
                            return Json(new { status = 302, url = "/Object/AdvancedDetails/" + model.IdObiektu });
                        }
                        else {
                            ModelState.AddModelError("NrNowegoWodomierza", "*Ten wodomierz jest już podpięty pod inny obiekt: " + item.ObiektId);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("NrNowegoWodomierza", "*Nie ma takiego wodomierza");
                    }
                }
            }
            return PartialView("_ChangeWaterMeterModalPartial", model);
        }
        //public IActionResult AttachToObject(string id)
        //{
        //    var model = new AttachWaterMeterToObjectViewModel { Id = Int32.Parse(id) };

        //    return PartialView("_AttachClientModalPartial", model);
        //}
        //[HttpPost]
        //public IActionResult AttachToClient(AttachClientToObjectViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (model.NumerKlienta.HasValue)
        //        {
        //            int count = dbContext.Klient.Where(k => k.IdKlienta == model.NumerKlienta).ToList().Count;
        //            if (count < 1)
        //            {
        //                ModelState.AddModelError("NumerKlienta", "*Nie ma takiego klienta");
        //            }
        //            else
        //            {
        //                var obj = dbContext.Obiekt.Where(o => o.Id == model.Id).ToList().Single();
        //                obj.KlientIdKlienta = model.NumerKlienta;
        //                dbContext.Obiekt.Update(obj);
        //                dbContext.SaveChanges();
        //                //return RedirectToAction("AdvancedDetails/" + obj.Id, "Object");
        //                return Json(new { status = 302, url = "/Object/AdvancedDetails/" + obj.Id });
        //            }
        //        }
        //    }
        //    return PartialView("_AttachClientModalPartial", model);
        //}
    }
}

Waterworks/Views/WaterMeter/Index.cshtml
@model PaginatedList<Waterworks.Models.View.WaterMeter.WaterMeterViewModel>

@{
    ViewData["Title"] = "Kartoteka wodomierzy";
}

<h2>Kartoteka wodomierzy</h2>
<hr />
<form asp-controller="WaterMeter" asp-action="Index" method="get">
    <div class="form-inline">
        <select class="form-control form-control-sm" id="exampleFormControlSelect1" name="currentCategory">
            <option value="NrWodomierza">Nr Wodomierza</option>
            <option value="IdObiektu">Id Obiektu</option>
            <option value="DataLegalizacji">Data Legalizacji</option>
            <option value="DataEwidencji">Data Ewidencji</option>
            <option value="TypWodomierza">Typ wodomierza</option>
        </select>
        <input class="form-control form-control-sm" type="text" name="searchString">
        <input type="submit" value="Wyszukaj" class="btn btn-primary" />
    </div>
</form>
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["WaterMeterNumberSortParam"]">Nr Wodomierza</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["ObjectIdSortParam"]">Id obiektu</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["LegalizationDateSortParam"]">Data legalizacji</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["RecordDateSortParam"]">Data ewidencji</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["WaterMeterTypeSortParam"]">Typ wodomierza</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NrWodomierza)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ObiektId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataLegalizacji)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataEwidencji)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypWodomierza)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Szczegóły</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-currentCategory="@ViewData["CurrentCategory"]"
   class="btn btn-default @prevDisabled">
    Poprzedni
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-currentCategory="@ViewData["CurrentCategory"]"
   class="btn btn-default @nextDisabled">
    Następny
</a>

Waterworks/Views/WaterMeter/_ChangeWaterMeterModalPartial.cshtml
@model Waterworks.Models.View.WaterMeter.ChangeWaterMeterViewModel
<!-- Modal -->
<div class="modal fade" id="attach-client" tabindex="-1" role="dialog" aria-labelledby="attachWaterMeterLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="attachWaterMeterLabel">
                    Wymień wodomierz
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </h5>
            </div>
            <div class="modal-body">
                <form asp-controller="WaterMeter" asp-action="ChangeWaterMeter">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <div class="form-group">
                        <label asp-for="NrWodomierza"></label>
                        <input asp-for="NrWodomierza" value="@Model.NrWodomierza" class="form-control" readonly />
                        <span asp-validation-for="NrWodomierza" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TypWodomierza"></label>
                        <input asp-for="TypWodomierza" value="@Model.TypWodomierza" class="form-control" readonly />
                        <span asp-validation-for="TypWodomierza" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NrNowegoWodomierza"></label>
                        <input asp-for="NrNowegoWodomierza" class="form-control" />
                        <span asp-validation-for="NrNowegoWodomierza" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="IdObiektu" class="form-control" value="@(Model.IdObiektu)" type="hidden" />
                        <span asp-validation-for="IdObiektu" class="text-danger"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
                <button type="button" class="btn btn-primary" data-save="modal">Zapisz</button>
            </div>
        </div>
    </div>
</div>

Waterworks/Views/WaterMeter/_List.cshtml
@model IEnumerable<Waterworks.Models.View.WaterMeter.WaterMeterViewModel>
<br>
@*<div id="modal-placeholder"></div>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NrWodomierza)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataLegalizacji)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataEwidencji)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypWodomierza)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NrWodomierza)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataLegalizacji)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataEwidencji)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypWodomierza)
                </td>
                <td>
                    <button type="button" class="btn btn-link"
                            data-toggle="ajax-modal" data-target="#attach-watermeter"
                            data-url="@Url.Action("ChangeWaterMeter","WaterMeter", new { objectId = item.ObiektId, oldWaterMeterNumber = item.NrWodomierza, oldWaterMeterType = item.TypWodomierza })">
                        Wymień
                    </button>
                    @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |*@
                    <a asp-controller="Object" asp-action="DetachWaterMeter" asp-route-id="@item.Id">Odepnij</a>
                    @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>
    <script src="~/js/modal.js"></script>